# 1. Write a program to generate a 6-digit random secure OTP.

In [4]:
import numpy as np
import secrets
otp=secrets.randbelow(1000000)
def hill_cipher(otp, key):
    key_matrix = np.array(key).reshape(2, 2)
    otp_digits = [int(d) for d in str(otp).zfill(6)]
    otp_matrix = np.array(otp_digits).reshape(3, 2)
    encrypted_matrix = np.dot(otp_matrix, key_matrix) % 10
    encrypted_otp = ''.join(str(d) for d in encrypted_matrix.flatten())
    return encrypted_otp
key = [6, 24, 1, 13]
encrypted_otp = hill_cipher(otp, key)
print(f"Generated OTP: {otp}")
print(f"Encrypted OTP: {encrypted_otp}")
    

Generated OTP: 852455
Encrypted OTP: 376055


# 2. Write a program to pick a random character from a user-supplied string.

In [5]:
import random
user_String=input("Enter a string : ")
randChar=random.choice(user_String)
print(user_String)
print(randChar)

bilal
l


# 3. Write  a program to generate a random password that meets the following conditions:
    a. Password length must be 10 characters long.
    b. It must contain at least 2 uppercase letters, 1 digit, and 1 special symbol.

In [6]:
import string
dig=string.digits
calph=string.ascii_uppercase
salph=string.ascii_lowercase
spelsy='@#$&'
s=[]
for i in range(10):
    if i <= 1:
        s.append(secrets.choice(calph))
    if i==2:
        s.append(secrets.choice(dig))
    if i==3:
        s.append(secrets.choice(spelsy))
    if i>=4:
        s.append(secrets.choice(dig+spelsy+salph+calph))
random.shuffle(s)        
psswd="".join(s)

key = [int(x) for x in random.sample(range(100), 100)]
pm=[ord(c) for c in psswd]
print(pm)
m1=np.array(key).reshape(10, 10)
print(m1)
prodmetrix=np.dot(pm,m1)%26
print(prodmetrix)
ciphertext="".join(chr(d+65) for d in prodmetrix.flatten())
print(f"Generated Password: {psswd}")
print(f"Encrypted Password: {ciphertext}")

[74, 70, 98, 65, 57, 75, 102, 113, 112, 35]
[[45  5 47 69 10 21 90 84 86 19]
 [41  9 74 65 44 18 49 93 52 39]
 [87 79 64 53 59 37 60 22 33 99]
 [27 63 58 81 28  1 71 43 91 98]
 [11 35 17 68 13 88 32 62  8 78]
 [72 97 50 83 38 14 75 36 70 95]
 [80 15  0 16 96 82 20 76 89  2]
 [57 40 42 73 51 48 31 66  3  6]
 [ 7 46 29  4 92 24 77 85 34 23]
 [67 30 54 12 56 94 25 61 26 55]]
[16 13 23 15 10 19 20 24 20  8]
Generated Password: JFbA9Kfqp#
Encrypted Password: QNXPKTUYUI


# 4. Given two lists of numbers, write a program to create a new list containing oddnumbers from the first list and even numbers from the second list.

In [7]:
l1=[64,46,94,98,76,74,974]
l2=[54,3,59,46,26,7,9,79,49,78]
l3=[]
n=max(len(l1),len(l2))
i=0
while i <n:
    if i < len(l1):
        if i%2==0:l3.append(l1[i])
    if i%2 !=0:l3.append(l2[i])
    i+=1
print(l3)

[64, 3, 94, 46, 76, 7, 974, 79, 78]


# 5. Write a program to create a numpy array and return an array of odd rows and evencolumns from the numpy array.

In [8]:
ar1=np.array(l1)
print(ar1)
ar2=np.array(l2).reshape(5,2)
print(ar2)

[ 64  46  94  98  76  74 974]
[[54  3]
 [59 46]
 [26  7]
 [ 9 79]
 [49 78]]


# 6. Write a program to create a numpy array and sort it as per the following cases:
    a. Case 1: Sort the array by the second row.
    b. Case 2: Sort the array by the second column.


In [9]:
array_1=np.array([[34,21,32,41,25],
                 [14,42,43,14,31],
                 [54,45,52,42,23],
                 [33,15,51,31,35],
                 [21,52,33,13,23]])
print("Original Array:")
print(array_1)
def marge(arr,low,mid,high):
    temp=[]
    i=low
    j=mid+1
    while i<=mid and j<=high:
        if arr[i]<=arr[j]:
            temp.append(arr[i])
            i+=1
        else:
            temp.append(arr[j])
            j+=1
    while i<=mid:
        temp.append(arr[i])
        i+=1
    while j<=high:
        temp.append(arr[j])
        j+=1
        j+=1
    for i in range(len(temp)):
        arr[low+i]=temp[i]

def marge_sort(arr, low,high):
    if low>=high:
        return
    mid=(low+high)//2
    marge_sort(arr,low,mid)
    marge_sort(arr,mid+1,high)
    marge(arr,low,mid,high)

array_1=array_1.flatten()
marge_sort(array_1,0,len(array_1)-1)
print("Sorted Array:")
print(array_1.reshape(5,5)) 

Original Array:
[[34 21 32 41 25]
 [14 42 43 14 31]
 [54 45 52 42 23]
 [33 15 51 31 35]
 [21 52 33 13 23]]
Sorted Array:
[[13 14 14 15 21]
 [21 23 23 25 31]
 [31 32 33 33 34]
 [35 41 42 42 43]
 [51 52 54 54 54]]
