# 1. Write a program to generate a 6-digit random secure OTP.

In [21]:
import numpy as np
import secrets
otp=secrets.randbelow(1000000)
def hill_cipher(otp, key):
    key_matrix = np.array(key).reshape(2, 2)
    otp_digits = [int(d) for d in str(otp).zfill(6)]
    otp_matrix = np.array(otp_digits).reshape(3, 2)
    encrypted_matrix = np.dot(otp_matrix, key_matrix) % 10
    encrypted_otp = ''.join(str(d) for d in encrypted_matrix.flatten())
    return encrypted_otp
key = [6, 24, 1, 13]
encrypted_otp = hill_cipher(otp, key)
print(f"Generated OTP: {otp}")
print(f"Encrypted OTP: {encrypted_otp}")
    

Generated OTP: 948824
Encrypted OTP: 886660


# 2. Write a program to pick a random character from a user-supplied string.

In [23]:
import random
user_String=input("Enter a string : ")
randChar=random.choice(user_String)
print(user_String)
print(randChar)

Bilal ahmad
h


# 3. Write  a program to generate a random password that meets the following conditions:
    a. Password length must be 10 characters long.
    b. It must contain at least 2 uppercase letters, 1 digit, and 1 special symbol.

In [ ]:
import string
dig=string.digits
calph=string.ascii_uppercase
salph=string.ascii_lowercase
spelsy='@#$&'
s=[]
for i in range(10):
    if i <= 1:
        s.append(secrets.choice(calph))
    if i==2:
        s.append(secrets.choice(dig))
    if i==3:
        s.append(secrets.choice(spelsy))
    if i>=4:
        s.append(secrets.choice(dig+spelsy+salph+calph))
random.shuffle(s)        
psswd="".join(s)

key = [int(x) for x in random.sample(range(100), 100)]
pm=[ord(c) for c in psswd]
print(pm)
m1=np.array(key).reshape(10, 10)
print(m1)
prodmetrix=np.dot(pm,m1)%26
print(prodmetrix)
ciphertext="".join(chr(d+65) for d in prodmetrix.flatten())
print(f"Generated Password: {psswd}")
print(f"Encrypted Password: {ciphertext}")

[84, 57, 88, 89, 86, 64, 54, 50, 48, 72]
[[65 75 52 12 76 20 36 74 40  2]
 [78  0 64 14  4 61 16 18 82 80]
 [19 34 23 27 54  1 71 24 84 72]
 [73  8 94 98 58 57 91 49 53 66]
 [42 10 47 48 83 35  5 88 15 37]
 [89 87 43 79 99 39 26 11 22 90]
 [96 69 32 67 97 45 25  9 68 51]
 [ 3 63 17 59 21  7 41  6 50 92]
 [81 85 77 56 28 62 13 30 86 46]
 [95 70 31 60 55 38 33 44 29 93]]
[25  6 10 18 18  6 23  3 25 18]
Generated Password: T9XYV@620H
Encrypted Password: ZGKSSGXDZS


# 4. Given two lists of numbers, write a program to create a new list containing oddnumbers from the first list and even numbers from the second list.

In [192]:
l1=[64,46,94,98,76,74,974]
l2=[54,3,59,46,26,7,9,79,49,78]
l3=[]
n=max(len(l1),len(l2))
i=0
while i <n:
    if i < len(l1):
        if i%2==0:l3.append(l1[i])
    if i%2 !=0:l3.append(l2[i])
    i+=1
print(l3)

[64, 3, 94, 46, 76, 7, 974, 79, 78]


# 5. Write a program to create a numpy array and return an array of odd rows and evencolumns from the numpy array.

In [204]:
ar1=np.array(l1)
print(ar1)
ar2=np.array(l2).reshape(5,2)
print(ar2)

[ 64  46  94  98  76  74 974]
[[54  3]
 [59 46]
 [26  7]
 [ 9 79]
 [49 78]]


# 6. Write a program to create a numpy array and sort it as per the following cases:
    a. Case 1: Sort the array by the second row.
    b. Case 2: Sort the array by the second column.


In [217]:
array_1=np.array([100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1]).reshape(10,10)
print("Original Array:")
print(array_1)
sorted_by_second_row = np.sort(array_1, axis=1)
print("Array sorted by the second row:")
print(sorted_by_second_row)

Original Array:
[[100  99  98  97  96  95  94  93  92  91]
 [ 90  89  88  87  86  85  84  83  82  81]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 70  69  68  67  66  65  64  63  62  61]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 50  49  48  47  46  45  44  43  42  41]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 30  29  28  27  26  25  24  23  22  21]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 10   9   8   7   6   5   4   3   2   1]]
Array sorted by the second row:
[[ 91  92  93  94  95  96  97  98  99 100]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 11  12  13  14  15  16  17  18  19  20]
 [  1   2   3   4   5   6   7   8   9  10]]
